package com.neo.exchangeMonitoring.utils

enum class SortingStates {
    SORTBYALPHABETINASCENDINGORDER,
    SORTBYALPHABETINDESCENDINGORDER,
    SORTBYVALUESINASCENDINGORDER,
    SORTBYVALUESINDESCENDINGORDER
}